# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: false   # <- ensure stop
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.2
      goal: 0.02
      trajectory: 0.05


gripper_controller:
  ros__parameters:
    joint: joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    goal_tolerance: 0.01
    max_effort: 0.0
    allow_stalling: false

