###############################################
# MoveIt Servo config for: arm + tool0
###############################################

# --- Timing ---
publish_period: 0.01                # 100 Hz Servo loop
max_expected_latency: 0.1

# --- Input commands ---
# You publish TwistStamped in real units (m/s, rad/s)
command_in_type: "speed_units"
require_enable: false
# These scales are used only if command_in_type == "unitless"
scale:
  linear: 0.2
  rotational: 0.8
  joint: 0.5

# --- Output to your controller ---
command_out_type: "trajectory_msgs/JointTrajectory"
command_out_topic: "/arm_controller/joint_trajectory"
publish_joint_positions: true
publish_joint_velocities: false
publish_joint_accelerations: false

# --- Smoothing (recommended) ---
use_smoothing: true
smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"

# --- Planning scene ownership ---
# MoveGroup is your primary planning scene; let Servo be secondary.
is_primary_planning_scene_monitor: false
check_octomap_collisions: false

# --- MoveIt / frames / group ---
move_group_name: "arm"
planning_frame: "base_link"             # group planning frame
robot_link_command_frame: "base_link"   # frame of incoming twists
ee_frame_name: "tool0"                  # your EEF link

# --- Singularities & limits ---
lower_singularity_threshold: 90.0
hard_stop_singularity_threshold: 100.0
leaving_singularity_threshold_multiplier: 2.0
joint_limit_margins: [0.01]             # safety margin to joint limits

# --- Topics (relative to node name, e.g. /servo_node_main/...) ---
cartesian_command_in_topic: "~/delta_twist_cmds"
joint_command_in_topic: "~/delta_joint_cmds"
joint_topic: "/joint_states"
status_topic: "~/status"

# --- Collision scaling ---
check_collisions: false
collision_check_rate: 10.0
self_collision_proximity_threshold: 0.002   # 2 mm
self_collision_proximity_threshold: 0.002   # 2 mm
